### ISSUE TITLE
Incompatibility with CustomFog

### ISSUE THREAD

**Issue by JosefLitos** [kerudion/chunksfadein#30]
**What is the issue?**
Even when I disable the `FadeIn` and use animation only, it still crashes when loading into a world.

**Conditions to reproduce**
download [CustomFog](https://github.com/helpimnotdrowning/custom-fog/releases/tag/2.2.0-1.19.3)

**Only one error before crashing**
```log
[22:11:09] [Render thread/INFO]: [Custom Fog] Overwriting sodium fog shader
[22:11:09] [Render thread/INFO]: [Custom Fog] Overwriting sodium fog shader
[22:11:09] [Render thread/INFO]: OpenGL debug message: id=3, source=SHADER COMPILER, type=ERROR, severity=HIGH, message='0:66(14): error: no matching function for call to `_linearFog(vec4, float, vec4, float, float, float)'; candidates are:'
[22:11:09] [Render thread/INFO]: OpenGL debug message: id=4, source=SHADER COMPILER, type=ERROR, severity=HIGH, message='0:66(14): error:    vec4 _linearFog(vec4, float, vec4, float, float)'
[22:11:09] [Render thread/WARN]: Shader compilation log for sodium:blocks/block_layer_opaque.fsh: 0:66(14): error: no matching function for call to `_linearFog(vec4, float, vec4, float, float, float)'; candidates are:
0:66(14): error:    vec4 _linearFog(vec4, float, vec4, float, float)
[22:11:09] [Render thread/ERROR]: Unreported exception thrown!
java.lang.RuntimeException: Shader compilation failed, see log for details
	at me.jellysquid.mods.sodium.client.gl.shader.GlShader.<init>(GlShader.java:34) ~[sodium-fabric-mc1.19.3-0.4.9+build.23.jar:?]
	at me.jellysquid.mods.sodium.client.gl.shader.ShaderLoader.loadShader(ShaderLoader.java:22) ~[sodium-fabric-mc1.19.3-0.4.9+build.23.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.createShader(ShaderChunkRenderer.java:50) ~[sodium-fabric-mc1.19.3-0.4.9+build.23.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.compileProgram(ShaderChunkRenderer.java:38) ~[sodium-fabric-mc1.19.3-0.4.9+build.23.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.begin(ShaderChunkRenderer.java:72) ~[sodium-fabric-mc1.19.3-0.4.9+build.23.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.RegionChunkRenderer.render(RegionChunkRenderer.java:66) ~[sodium-fabric-mc1.19.3-0.4.9+build.23.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.renderLayer(RenderSectionManager.java:289) ~[sodium-fabric-mc1.19.3-0.4.9+build.23.jar:?]
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.drawChunkLayer(SodiumWorldRenderer.java:215) ~[sodium-fabric-mc1.19.3-0.4.9+build.23.jar:?]
	at net.minecraft.class_761.method_3251(class_761.java:15512) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_22710(class_761.java:1246) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1085) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:864) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1193) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:781) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) ~[minecraft-1.19.3-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[minecraft-1.19.3-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.13.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.13.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.13.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[NewLaunch.jar:?]
[22:11:10] [Server thread/INFO]: Stopping server
```

**CustomFog simplest config possible**
```json
{
  "defaultConfig": {
    "enabled": false
  },
  "waterConfig": {
    "enabled": false
  },
  "snowConfig": {
    "enabled": false
  },
  "dimensions": [
  ],
  "videoOptionsButton": false,
  "hasClosedToast": true,
  "hasAcknowledgedSodium": true
}
```

**Comment by JosefLitos** [comment]
not sure whether this is something with CustomFog breaking minecraft default methods, tell me if I should raise an issue over there.

**Comment by kerudion** [comment]
Hi! As I know, it's not possible to mixin in a mixin, so I can't fix this issue because Custom Fog is replacing the whole fog shader. I think, it's better for Custom fog developer to fix this issue.

While this issue is not fixed, you can use this [mod](https://modrinth.com/mod/simplefog) which works with Chunks fade in perfectly.
